### ISSUE TITLE
wpecbf auto fix does not work

### ISSUE THREAD

**Issue by marijnbent** [wpengine/wpengine-coding-standards#4]
After running `wpecs --standard="WP-Engine-Strict" .` and generating a list of violations, running the `wpecbf .` command results in the following error. Anyone with the same problem?  
```
PHPCBF CAN FIX THE 18 MARKED SOURCES AUTOMATICALLY (4541 VIOLATIONS IN TOTAL)
---------------------------------------------------------------------------------------

Time: 630ms; Memory: 28MB

Reports can be found in the target directory as 'report-full.txt' and 'report-source.txt'

Try using 'wpecbf' to attempt fix the sniff violations automatically.
```

```
> wpecbf .
WP Engine Coding Standards
Version 1.0.0

Attempting to beautify against WP Engine Coding Standards

PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Trying to access array offset on value of type bool in /Users/marijnbent/Projects/wpengine-coding-standards/vendor/wp-coding-standards/wpcs/WordPress/Sniff.php on line 1252 in /Users/marijnbent/Projects/wpengine-coding-standards/vendor/squizlabs/php_codesniffer/src/Runner.php:606
Stack trace:
#0 /Users/marijnbent/Projects/wpengine-coding-standards/vendor/wp-coding-standards/wpcs/WordPress/Sniff.php(1252): PHP_CodeSniffer\Runner->handleErrors(8, 'Trying to acces...', '/Users/marijnbe...', 1252, Array)
#1 /Users/marijnbent/Projects/wpengine-coding-standards/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/Files/FileNameSniff.php(194): WordPress\Sniff->is_test_class(101)
#2 /Users/marijnbent/Projects/wpengine-coding-standards/vendor/wp-coding-standards/wpcs/WordPress/Sniff.php(840): WordPress\Sniffs\Files\FileNameSniff->process_token(0)
#3 /Users/marijnbent/Projects/wpengine-coding-standards/vendor/squizlabs/php_codesniffer/src/Files/File.php(496): WordPress\ in /Users/marijnbent/Projects/wpengine-coding-standards/vendor/squizlabs/php_codesniffer/src/Runner.php on line 606

Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Trying to access array offset on value of type bool in /Users/marijnbent/Projects/wpengine-coding-standards/vendor/wp-coding-standards/wpcs/WordPress/Sniff.php on line 1252 in /Users/marijnbent/Projects/wpengine-coding-standards/vendor/squizlabs/php_codesniffer/src/Runner.php:606
Stack trace:
#0 /Users/marijnbent/Projects/wpengine-coding-standards/vendor/wp-coding-standards/wpcs/WordPress/Sniff.php(1252): PHP_CodeSniffer\Runner->handleErrors(8, 'Trying to acces...', '/Users/marijnbe...', 1252, Array)
#1 /Users/marijnbent/Projects/wpengine-coding-standards/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/Files/FileNameSniff.php(194): WordPress\Sniff->is_test_class(101)
#2 /Users/marijnbent/Projects/wpengine-coding-standards/vendor/wp-coding-standards/wpcs/WordPress/Sniff.php(840): WordPress\Sniffs\Files\FileNameSniff->process_token(0)
#3 /Users/marijnbent/Projects/wpengine-coding-standards/vendor/squizlabs/php_codesniffer/src/Files/File.php(496): WordPress\ in /Users/marijnbent/Projects/wpengine-coding-standards/vendor/squizlabs/php_codesniffer/src/Runner.php on line 606

```

**Comment by ChrisWiegman** [comment]
This looks like something has been corrupted in the `vendor` folder. I would suggest trying to remove the `vendor` folder and then run `composer install` from the coding standards folder.

If that doesn't work, I have a pull request in that should make these standards much easier to use in general next week.
